### ISSUE TITLE
Server problems

### ISSUE THREAD

**Issue by artifexJuls** [Brambles-cat/AdvancedChorusFruit#2]
Hello, i have server on 1.19 versions and users can not use chorus to teleport to warp checkpoint. But i (and admins other) can.
Players can create warp place but can not use chorus to teleport there. And i have no idea why. There's no *admin only* config.

**Comment by Brambles-c** [comment]
Thanks for the report, I'll see to it that it'll be resolved soon

**Comment by artifexJuls** [comment]
Nice! I think the problem is somewhere in creative moment, cuz when we(admins) are in survival mode - teleport don't work on us too. It works only in creative.

**Comment by Brambles-c** [comment]
I figured out the issue, it's not an admin thing. When changing the checkpoint there's an extra decimal added in the coordinate strings which cause internal errors. The short-term fix for this is to remove the checkpoint (via command) and then setting it again with the named eye
Or you can manually fix it by going into the plugin folder -> AdvancedChorusFruit -> TeleportData.json and removing the trailing "0.5" that'll be in the Z coordinate part of the string
(X.5|Y.0|Z.00.5)

I'll make sure to update the fix in curse forge but it'll take a bit to be approved

**Comment by artifexJuls** [comment]
![123](https://user-images.githubusercontent.com/116838884/221640511-bb061622-a3b5-4c15-9e87-26aee2e47a1f.jpg)
nope. it still wont work when i in survival mode. i add screen of config.  btw - can you add to cofig optional so we can decide - can player create warp, see the list of warp and etc. or it's only for admins and they can only teleport with help of chorus warp not create one? that woud be awesome, more config content and permisions <3

**Comment by Brambles-c** [comment]
Hmm, are there any errors in the console that are turning up, or maybe it could be some other plugins that are preventing it from working? Maybe try isolating the plugin and see if it works normally? I'll keep trying some different tests. Also, I'll definitely see if if I can add more config options, thanks for the suggestion

**Comment by artifexJuls** [comment]
ow, yeah, there is an error
![photo_2023-02-27_23-44-06](https://user-images.githubusercontent.com/116838884/221692673-401783c3-82c2-439e-9fe9-0e4409631a8d.jpg)

**Comment by Brambles-c** [comment]
It looks like the error happens when you're holding a singular fruit. Thanks for that, I've published a release on github with the fixes, however, you'll have to delete the AdvancedChorusFruit folder (not just the json file), as it uses a different data structure. I'll be sure to get another version up with more admin configs and perms soon

**Comment by artifexJuls** [comment]
errors are still there BUT now everything works normaly in any gamemod! Tnx <3 
![45](https://user-images.githubusercontent.com/116838884/221827055-2f839821-af8a-4753-92e1-903dda9b856e.jpg)

**Comment by Brambles-c** [comment]
What causes the error to occur? Can you provide some more information on how you're using the anvil, what item, name, etc?

**Comment by artifexJuls** [comment]
yes, so error pops up when i put an ender eye in anvil, i don't even start to write *set* or smt, same with chorus. i place anvil. open it. place item and - error all over console

**Comment by artifexJuls** [comment]
Hello, just wanted to update that i tried to ban simple players from using "removeLocation","listwarps" and etc in luckperms permissions but it didn't work, although i set it up  to false, so a more open settings in plugin config to ban players from using that and create they own warps would be nice 👍 🥲 thanks ❤️

**Comment by Brambles-c** [comment]
I just published another release on GitHub with permission commands. Unfortunately I was unable to replicate the error you found with the anvil, but I believe now it should work even if you do see errors. Please let me know if there's anything wrong or if you have other suggestions once you try it! (Also I slightly changed a few command names) (Also also you'll have to delete the AdvancedChorusFruit folder again, but if you have coordinate data saved you can paste it over to the new one that'll be created)

**Comment by artifexJuls** [comment]
hello, yeah the errors in console in general do not cause problems with the plugin to work well, they just there for some reason lol. 
new permissions work realy good, players without them can teleport but can not create warp on there own, thank you very much <3 
the only small problem is that each player has to be manually banned while on the server because it is not possible to ban by nickname in the config, players are banned and written down into permissions by there unique numbers. The system is a little heavy when you have many players, because it is done by hand, but still - it works and it's amazing, thnx <3

**Comment by Brambles-c** [comment]
Thanks for the feedback. I tried staying away from using player names since players are able to change them, but the id can't be changed. I am currently looking into getting rid of the anvil error messages and setting default permissions so that there will be less manual permission editing. Thanks for opening this issue, glad I was able to fix these problems
